# Site settings
title: Pete Cruz
description: 'Software Engineer ranting about programming languages, concurrent, and distributed systems'
url: 'https://petesta.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Pete Cruz'
  email: iPetesta@gmail.com
  twitter_username: iPetesta
  github_username:  Petesta

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # Use Github Flavored Markdown
  input: GFM
  # Do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

google_analytics: UA-79714344-1
