# Site Settings
title: Pete Cruz
description: 'Software Engineer working at Caterpillar ranting about Vim, concurrency, systems, and programming languages'
url: 'https://blog.petesta.com'
baseurl: '/'
path_check: '/'
google_analytics: 'UA-79714344-1'
disqus_shortname: 'petesta'
timezone: America/Los_Angeles

# Author Settings
author:
  name: 'Pete Cruz'
  email: iPetesta@gmail.com
  github_username:  Petesta
  linkedin_username: petecruz

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build Settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # Use Github Flavored Markdown
  input: GFM
  # Do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jemoji']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
