# Site Settings
title: Pete Cruz
description: 'Software Engineer ranting about Vim, concurrency, systems, and programming languages'
url: 'https://petesta.github.io'
baseurl: '/'
timezone: America/Los_Angeles
# disqus_shortname: 'your-disqus-name'

# Author Settings
author:
  name: 'Pete Cruz'
  email: iPetesta@gmail.com
  github_username:  Petesta
  linkedin_username: petecruz
  twitter_username: iPetesta

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build Settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # Use Github Flavored Markdown
  input: GFM
  # Do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
